#ifndef SHARED_BINDINGS_INC      
#define SHARED_BINDINGS_INC

/* ------------ Set 0 -------------------------------- */
#define SET_GLOBAL                     0

#define BIND_UBO                       0   
#define BIND_WBOIT_COLOR               1  
#define BIND_WBOIT_REVEAL              2   
#define BIND_HEAD_ALBEDO               3   
#define BIND_HAIR_ALBEDO               4  
#define BIND_HAIR_NORMAL               5
#define BIND_HAIR_TANGENT              6
#define BIND_HAIR_AO 				   7

#endif 
