#ifndef SHARED_BINDINGS_INC      
#define SHARED_BINDINGS_INC

/* ------------ Set 0 -------------------------------- */
#define SET_GLOBAL						0

#define BIND_VERTEX_POSITION 			0
#define BIND_VERTEX_NORMAL				1
#define BIND_VERTEX_TEXCOORD			2
#define BIND_VERTEX_COLOR				3

#define BIND_UBO						4   
#define BIND_WBOIT_COLOR				5  
#define BIND_WBOIT_REVEAL				6   
#define BIND_HEAD_ALBEDO				7   
#define BIND_HAIR_ALBEDO				8  
#define BIND_HAIR_NORMAL				9
#define BIND_HAIR_DIRECTION				10
#define BIND_HAIR_AO 					11
#define BIND_HAIR_DEPTH 				12
#define BIND_HAIR_ROOT 					13
#define BIND_HAIR_ID 					14
#define BIND_HAIR_FLOW 					15

#define BIND_ENV_MAP 					16

#endif 
